### ISSUE TITLE
Convert JSON to ARFF?

### ISSUE THREAD

**Issue by leandroricardo** [julien-f/human-format#4]
hello ... I can not convert a json file to ARFF using your example. The result is that I have this: [ '\n', '@DATA', '\n' ]

I can use the parse, but not the format.

thanks for help

**Comment by julien-f** [comment]
> This issue is not in the correct repository, it should have been there https://github.com/julien-f/js-arff
> It is my fault because the link in the README was incorrect, it has been fixed now.

You mean the example in the README?
I can parse it successfully and then format it again without any problems.
